### ISSUE TITLE
What's your tensorflow version?

### ISSUE THREAD

**Issue by XiaodanLi001** [papermsucode/advhat#1]
Hi, thank you for your contribution. When I trying to reproduce your work, the tf model can't be loaded with error "InvalidArgumentError (see above for traceback): NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv0 = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_image_input_0_0/_77, W_conv0). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.)."  I think this is caused by the tf version. So, what's your tensorflow version? My version is tf 1.4.0.

**Comment by Polkach** [comment]
Hi! We use 1.13.1 version of TensorFlow.

**Comment by XiaodanLi001** [comment]
> Hi! We use 1.13.1 version of TensorFlow.

Thank you for your reply. After updating the tf version to 1.13.1, the error has gone. But I'm a little confused. In step 3, it generates img_with_hat_only_aligned.png as well as img_with_hat_only_mask.png. And in step 5, PATH_TO_THE_PREPARED_IMAGED_WITH_HAT, this means img_with_hat_only_aligned.png or img_with_hat_only_mask.png? I guess it's the former one. Another question is, the first step seems to be unnecessary for training adv_hat, I'm not sure if there's any mistakes in my reproducing.

**Comment by Polkach** [comment]
"img_with_hat_only_mask.png" is needed to find the parameters of mask placement only.
You made a photo with an example sticker during the first step. You need to find parameters that make  "img_with_hat_only_mask.png" looking like the prepared photo with an example sticker in terms of sticker area and location.

**Comment by XiaodanLi001** [comment]
> "img_with_hat_only_mask.png" is needed to find the parameters of mask placement only.
> You made a photo with an example sticker during the first step. You need to find parameters that make "img_with_hat_only_mask.png" looking like the prepared photo with an example sticker in terms of sticker area and location.

I see. Thank you so much for your help.

**Comment by Polkach** [comment]
All this activity is needed because of sticker looks different after face alignment to the standard template for recognition since the form of each face is unique.
Certainly, you can use default parameters. We believe that they are quite good. Moreover, one photo is enough to prepare the attack. But we can not be sure that all work if you simplify the procedure.
So you can try the first attack with default parameters using one prepared image in a hat. Mostly it will work.
