### ISSUE TITLE
Question about the bending parabolic transformation

### ISSUE THREAD

**Issue by ultimatedigiman** [papermsucode/advhat#13]
as I know
assume
<img width="80" alt="image" src="https://user-images.githubusercontent.com/67790229/110900886-6e7f9c80-833e-11eb-8486-0aad4cdece81.png">
arc length
<img width="408" alt="image" src="https://user-images.githubusercontent.com/67790229/110900960-8525f380-833e-11eb-8fea-d3a4befebe41.png">
It is the same as the formula in the paper
so we get 
![1](https://user-images.githubusercontent.com/67790229/109105911-c11b5f00-7769-11eb-8f12-1cc394a7e27e.jpg)
As described in this figure:
![4](https://user-images.githubusercontent.com/67790229/109106201-456de200-776a-11eb-8a89-d363b079f9c8.jpg)
but the equetion in the paper is:
![3](https://user-images.githubusercontent.com/67790229/109106040-fd4ebf80-7769-11eb-8b5f-f07fc7747584.jpg)
in which the order of `x` and `x'` is reversed
So how can I get the formula in the paper？

**Comment by Polkach** [comment]
Hi! I don't see any contradictions between our formulas:
1) We use |x| since we need to calculate the arc length for the left side of the arc too. Since x^2 is equal to |x|^2, we use x^2.
2) ln(1/(2a)) is equal to -ln(2a), so there is no issue with term sign.
3) Finally if you multiply each term inside brackets by the a then the final formula becomes equal

**Comment by ultimatedigiman** [comment]
Hi!
All I mean is that the **order** of `x` and `x'` is different
`x'` represents the  x coordinate of the new point **after** the parabolic transformation
`x`  represents the x coordinate of the old point **before** the parabolic transformation and the **arc length**
description:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/67790229/109602975-15ed1a00-7b5c-11eb-902e-bcb6e8e8f965.png">
so the formulas are:
* **original paper**
<img width="477" alt="image" src="https://user-images.githubusercontent.com/67790229/109602136-dffb6600-7b5a-11eb-9413-a805676ef9f0.png">

* **mine**
<img width="508" alt="image" src="https://user-images.githubusercontent.com/67790229/109602364-f1dd0900-7b5a-11eb-88bc-911e227c1a3b.png">

**Comment by Polkach** [comment]
@ultimatedigiman You are right. Thank you for your find! The code realization is correct but there is a misstep in the paper text
