### ISSUE TITLE
demo.py error: NHWC tensor format for now

### ISSUE THREAD

**Issue by FossilDaddy** [papermsucode/advhat#3]
when i run demo.py, error happened: Generic conv implementation only supports NHWC tensor format for now, node conv0  ,  in line 90 , sess.run(embedding,feed_dict={image_input:batch,keep_prob:1.0,is_train:False}) .
when i hide this line (90) , it can work well, show rectangle face correctly. 

what' wrong ? my tensorflow verson is 1.14.0 .,Python 3.6.
thanks a lot.

**Comment by fatheral** [comment]
Hello,
- we used 1.13.1 version of TensorFlow;
- only using GPU when working with TF model.

**Comment by FossilDaddy** [comment]
thanks for your reply. I try reinstalling Tensorflow 1.13.1, but same error  exists. by the way, my Os is Win10,support GPU.

**Comment by Polkach** [comment]
@FossilDaddy
Hello! Did you solve your issue?
