### ISSUE TITLE
Have you tried target attack?

### ISSUE THREAD

**Issue by XiaodanLi001** [papermsucode/advhat#5]
I'm wondering if this method can be applied to do physical target attack since this is more dangerous. I have tried to optimize the adv patch by force the face to target face, but the similarity never goes up to 0.55. Do you have any suggestions?

**Comment by fatheral** [comment]
Hi! A good question. Our main goal was to show the vulnerability of the best FaceID models to real-world adversarial attacks, and for that point untargeted attack was chosen as the one that can be enough for real applications.

As about targeted attacks we have done a few experiments, and have the following behavior: the targeted face similarity was high, but the similarity to the ground truth face was also not so small. Maybe some hyperparams needs to be tuned (additional to ones used in untargeted attack) for bigger gap between adversarial and targeted similarities I'm not sure. But as we were not concentrated on this scenario we didn't pay much attention to it.

If you have any progress / statistics for targeted attack - please let us know!

**Comment by XiaodanLi001** [comment]
> Hi! A good question. Our main goal was to show the vulnerability of the best FaceID models to real-world adversarial attacks, and for that point untargeted attack was chosen as the one that can be enough for real applications.
> 
> As about targeted attacks we have done a few experiments, and have the following behavior: the targeted face similarity was high, but the similarity to the ground truth face was also not so small. Maybe some hyperparams needs to be tuned (additional to ones used in untargeted attack) for bigger gap between adversarial and targeted similarities I'm not sure. But as we were not concentrated on this scenario we didn't pay much attention to it.
> 
> If you have any progress / statistics for targeted attack - please let us know!

When you testing targeted attack, what loss did you use? I just simply modified:
cos_loss = tf.reduce_sum(tf.multiply(embedding,orig_emb),axis=1)
to cos_loss = -tf.reduce_sum(tf.multiply(embedding,orig_emb),axis=1) 
since my target is to maximize the similarity between PATH_TO_THE_PREPARED_IMAGED_WITH_HAT and target anchor_face. But I have tested many times, the similarity never went higher than 0.6, which is different from your result. Do you have any suggestions?

**Comment by Polkach** [comment]
You are doing all right. Our results are similar to yours. In our experiments, we use loss function which is equal to lambda_1*cosine_sim(original, attack_im)-lambda_2*cosine_sim(target, attack_im), sometimes it can slightly help.

Anyway, we did not present our results on targetted attacks before, thus any results can not differ from ours :)
