### ISSUE TITLE
Could not generate mask

### ISSUE THREAD

**Issue by TommyDong1998** [papermsucode/advhat#6]
I had a problem generating the face mask.  Can you give a list of what libraries are required for pip?

**Comment by TommyDong1998** [comment]
Here are the errors I get.
https://pastebin.com/F6GxkApQ
Also just to make sure.
When I run the attack command does the picture need the sticker on the hat? Is it possible for you to post example inputs?

**Comment by Polkach** [comment]
It seems like your TF version differs much. We use TensorFlow 1.14 in our experiments.
For attack.py script, you need a full-face photo in a hat (without any stickers on it). A sticker will be placed on this image during the attack (in the digital domain inside the code).
Please give us a response was it helpful or not.

**Comment by TommyDong1998** [comment]
I tried using TensorFlow 1.14.0 on Ubuntu 18.04.3 and I have the exact same error. Is it possible for you to provide sample images used attack.py?

**Comment by Polkach** [comment]
Just apply face_preparation.py for any frontal image without a hat. Don't use any args.

**Comment by Polkach** [comment]
You will receive a suitable image as a result.

**Comment by alexrider23** [comment]
I'm in the same group as him. Its still not working. This is the command I'm using.
python3 attack.py hat_aligned.png r100.pb --anchor_face no_hat_aligned.png

![image](https://user-images.githubusercontent.com/32995187/67522201-4f656980-f67a-11e9-9226-0d96bffcab08.png)
This is the images I'm providing.
Can you provide any clues as to why this is not working?
The result when I use the command is https://pastebin.com/z0mTV2iX . I'm using the correct version of tensorflow.

**Comment by Polkach** [comment]
As I understand, you are using CPU for the launch. This code can't be run on CPU since TensorFlow can't use NCHWorder on CPU.
Sorry, that I didn't understand earlier.
Maybe later we will release ArcFace TF-version with NHWC tensor order. But now it is impossible since we are on a business trip.

**Comment by alexrider23** [comment]
Hello,
So we have gotten a gpu version of tensor and are now encountering another error
`Traceback (most recent call last):
  File "attack.py", line 228, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "attack.py", line 144, in main
    fdict2[image_input] = prep(anch_im)
  File "attack.py", line 19, in prep
    return np.transpose(im,[2,0,1]).reshape((1,3,112,112))*2-1
ValueError: cannot reshape array of size 12544 into shape (1,3,112,112)
`
https://pastebin.com/iSudsvKs
Any clarifications would be greatly appreciated.
Thanks

**Comment by Polkach** [comment]
Looks like you have the wrong dimension of the input image. It should have 600x600x3 size.

**Comment by TommyDong1998** [comment]
I tried supplying a 600px by 600px png image and it still fails. Can you clarify what you mean by 3? Don't the face_preparation.py make the image suitable for attack.py?

**Comment by Angus1996** [comment]
> Hello,
> So we have gotten a gpu version of tensor and are now encountering another error
> `Traceback (most recent call last): File "attack.py", line 228, in <module> main(parse_arguments(sys.argv[1:])) File "attack.py", line 144, in main fdict2[image_input] = prep(anch_im) File "attack.py", line 19, in prep return np.transpose(im,[2,0,1]).reshape((1,3,112,112))*2-1 ValueError: cannot reshape array of size 12544 into shape (1,3,112,112) `
> https://pastebin.com/iSudsvKs
> Any clarifications would be greatly appreciated.
> Thanks

I have met the same problem, can you help me? thanks!

**Comment by TommyDong1998** [comment]
I resolved the issue by downgrading numpy to numpy==1.15.4 and sklearn==0.0. Also make sure cuda is installed.

**Comment by ziwenlu** [comment]
@TommyDong1998 l use the tensorflow 1.14.0 and when downgrading numpy to 1.15.4 and rerun the attack.py it shows me SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2022-10-27 20:45:13.012569: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
