### ISSUE TITLE
InsightFace model

### ISSUE THREAD

**Issue by XiaodanLi001** [papermsucode/advhat#7]
Hi, I'm correctly working on target attack with your method. I found it always fails when trying to 
attack other face recognition models, even though the logo is large. For example, I got 0.97 cos similarity on your model, but when applied to IR50 model in pytorch, the similarity only reached 0.42. So I'm wondering if your method only works for your model, because I did't manage to get a good mask on pytorch IR50 model even for untargeted attack. I'm wondering have you tried your method on other face recognition model.

**Comment by Polkach** [comment]
You can find experiments about the transferability of attack in the paper.
Briefly, as other adversarial attacks, this attack works worse on other models.
