### ISSUE TITLE
Problems with experimental results

### ISSUE THREAD

**Issue by LuGuo1920** [papermsucode/advhat#8]
When I used your code to experiment with my own photos, I printed out the stickers and pasted them on the hat. After taking photos again, the final similarity was 0.6, which was still very high. Is it just because of the problem with my printer? Or something else?

**Comment by Polkach** [comment]
Did you carefully reproduce all the steps from https://github.com/papermsucode/advhat/blob/master/Attack/README.md?
Maybe there are some issues with some of them?
