### ISSUE TITLE
the location of the sticker

### ISSUE THREAD

**Issue by liyue0213** [papermsucode/advhat#9]
how can i change the placement of the sticker ?

**Comment by fatheral** [comment]
@liyue0213 

Please use the special script `face_preparation.py` for it:

> You need to find parameters for the sticker position initialization. Use the next command to find these parameters:
> python3 face_preparation.py PATH_TO_THE_IMAGE_WITH_HAT_ONLY --mask
> It will show sticker placement with default parameters. Change parameters until the image looks like a prepared image with the sticker. You can see the parameters using --help flag.

But note that the new location could not be the good position to place the sticker because of the attention of the FaceID neural net.
